Dynamically scale Folder Icons for Toolbar buttons
linuxgurugamer/JanitorsCloset pull request #39
Opened 2024-02-28 20:33 UTC by KerballOne

The icons for the Application toolbar buttons can now scale with GameSettings.UI_Scale

2024-03-08 17:39 UTC, linuxgurugamer requested changes
You've induced a performance issue.  I saw at least 6-8 locations where  you have a multiplication (38 * UI_Scaler), please fix this by having a single line where the multiplications are done

2024-03-10 22:59 UTC, KerballOne commented
Fixed multiple lines of duplicate multiplication

2025-02-09 12:37 UTC, linuxgurugamer commented
I realize this has been here for a while, I expect to be able to work on it in the next few days

2026-07-14 17:49 UTC, linuxgurugamer commented
I just merged a different PR for performance issues, there are now some conflicts.  Can you take a look and resolve them?

2026-07-15 19:28 UTC, merged

2026-07-17 11:33 UTC, linuxgurugamer commented
This PR is causing hidden buttons to not show up in the folders.
I may need to revert it, can you take alook?